export const VERSION = '0.1.0';

export { FabricPhotoEditor } from './editor';
export type { FabricPhotoEditorProps } from './editor';
export { CanvasView } from './canvas-view';
export type { CanvasViewProps } from './canvas-view';
export { EditorProvider } from './provider';
export type { EditorProviderProps } from './provider';
export { useEditor, useEditorState, useEditorEvent, useToolSettings, useTheme } from './hooks';
export { DEFAULT_TOOL_SETTINGS, modeToTool, activateTool, applyColor } from './tool-settings';
export { useThemeState } from './theme';
export type { Theme, ThemeState } from './theme';
export { useShortcuts, TOOL_SHORTCUTS } from './shortcuts';
export type { ToolId, ToolSettings } from './tool-settings';
export { ColorPalette, PALETTE_COLORS } from './color-palette';
export type { ColorPaletteProps } from './color-palette';
export { Toolbar, TOOLS } from './toolbar';
export type { ToolDef } from './toolbar';
export { FloatingOptions } from './floating-options';
export { TopBar } from './top-bar';
export { ZoomControls } from './zoom-controls';
export { PropertiesPanel } from './properties-panel';
export { LayersPanel } from './layers-panel';
export type { LayersPanelProps } from './layers-panel';
export type { EditorUIState } from './context';
