import type { Canvas, Object as FabricObject } from './types/fabric';
import util from './lib/util';

/**
 * KeyMirror type - creates an object where keys and values are the same
 */
type KeyMirror<T extends readonly string[]> = {
    [K in T[number]]: K;
};

/**
 * Module names generated by keyMirror
 */
type ModuleNames = KeyMirror<
    [
        'MAIN',
        'IMAGE_LOADER',
        'CROPPER',
        'FLIP',
        'ROTATION',
        'FREE_DRAWING',
        'LINE',
        'ARROW',
        'TEXT',
        'ICON',
        'FILTER',
        'SHAPE',
        'MOSAIC',
        'PAN'
    ]
>;

/**
 * Command names generated by keyMirror
 */
type CommandNames = KeyMirror<
    [
        'CLEAR',
        'CLEAR_OBJECTS',
        'LOAD_IMAGE',
        'FLIP_IMAGE',
        'ROTATE_IMAGE',
        'ADD_OBJECT',
        'REMOVE_OBJECT',
        'APPLY_FILTER',
        'ZOOM'
    ]
>;

/**
 * Editor states generated by keyMirror
 */
type States = KeyMirror<
    [
        'NORMAL',
        'CROP',
        'FREE_DRAWING',
        'LINE',
        'ARROW',
        'MOSAIC',
        'TEXT',
        'SHAPE',
        'PAN'
    ]
>;

/**
 * Event names
 */
interface EventNames {
    readonly LOAD_IMAGE: string;
    readonly CLEAR_OBJECTS: string;
    readonly CLEAR_IMAGE: string;
    readonly START_CROPPING: string;
    readonly END_CROPPING: string;
    readonly FLIP_IMAGE: string;
    readonly ROTATE_IMAGE: string;
    readonly ADD_OBJECT: string;
    readonly SELECT_OBJECT: string;
    readonly REMOVE_OBJECT: string;
    readonly ADJUST_OBJECT: string;
    readonly START_FREE_DRAWING: string;
    readonly END_FREE_DRAWING: string;
    readonly START_LINE_DRAWING: string;
    readonly END_LINE_DRAWING: string;
    readonly START_PAN: string;
    readonly END_PAN: string;
    readonly START_ARROW_DRAWING: string;
    readonly END_ARROW_DRAWING: string;
    readonly START_MOSAIC_DRAWING: string;
    readonly END_MOSAIC_DRAWING: string;
    readonly EMPTY_REDO_STACK: string;
    readonly EMPTY_UNDO_STACK: string;
    readonly PUSH_UNDO_STACK: string;
    readonly PUSH_REDO_STACK: string;
    readonly ACTIVATE_TEXT: string;
    readonly APPLY_FILTER: string;
    readonly EDIT_TEXT: string;
    readonly MOUSE_DOWN: string;
    readonly CHANGE_ZOOM: string;
}

/**
 * Key codes
 */
interface KeyCodes {
    readonly Z: number;
    readonly Y: number;
    readonly SHIFT: number;
    readonly BACKSPACE: number;
    readonly DEL: number;
}

/**
 * Selection style for fabric objects
 */
interface SelectionStyle {
    readonly borderColor: string;
    readonly cornerColor: string;
    readonly cornerStrokeColor: string;
    readonly cornerSize: number;
    readonly padding: number;
    readonly originX: string;
    readonly originY: string;
    readonly transparentCorners: boolean;
    readonly cornerStyle: string;
}

/**
 * Fabric object options
 */
interface FObjectOptions {
    readonly SELECTION_STYLE: SelectionStyle;
}

/**
 * Reject messages for command operations
 */
interface RejectMessages {
    readonly flip: string;
    readonly rotation: string;
    readonly loadImage: string;
    readonly isLock: string;
    readonly undo: string;
    readonly redo: string;
}

/**
 * Main constants interface
 */
interface Consts {
    readonly moduleNames: ModuleNames;
    readonly commandNames: CommandNames;
    readonly eventNames: EventNames;
    readonly states: States;
    readonly keyCodes: KeyCodes;
    readonly fObjectOptions: FObjectOptions;
    readonly rejectMessages: RejectMessages;
    readonly MOUSE_MOVE_THRESHOLD: number;
}

const consts: Consts = {
    /**
     * Component names
     */
    moduleNames: util.keyMirror(
        'MAIN',
        'IMAGE_LOADER',
        'CROPPER',
        'FLIP',
        'ROTATION',
        'FREE_DRAWING',
        'LINE',
        'ARROW',
        'TEXT',
        'ICON',
        'FILTER',
        'SHAPE',
        'MOSAIC',
        'PAN'
    ) as ModuleNames,

    /**
     * Command names
     */
    commandNames: util.keyMirror(
        'CLEAR',
        'CLEAR_OBJECTS',
        'LOAD_IMAGE',
        'FLIP_IMAGE',
        'ROTATE_IMAGE',
        'ADD_OBJECT',
        'REMOVE_OBJECT',
        'APPLY_FILTER',
        'ZOOM'
    ) as CommandNames,

    /**
     * Event names
     */
    eventNames: {
        LOAD_IMAGE: 'loadImage',
        CLEAR_OBJECTS: 'clearObjects',
        CLEAR_IMAGE: 'clearImage',
        START_CROPPING: 'startCropping',
        END_CROPPING: 'endCropping',
        FLIP_IMAGE: 'flipImage',
        ROTATE_IMAGE: 'rotateImage',
        ADD_OBJECT: 'addObject',
        SELECT_OBJECT: 'selectObject',
        REMOVE_OBJECT: 'removeObject',
        ADJUST_OBJECT: 'adjustObject',
        START_FREE_DRAWING: 'startFreeDrawing',
        END_FREE_DRAWING: 'endFreeDrawing',
        START_LINE_DRAWING: 'startLineDrawing',
        END_LINE_DRAWING: 'endLineDrawing',
        START_PAN: 'startPan',
        END_PAN: 'endPan',
        START_ARROW_DRAWING: 'startArrowDrawing',
        END_ARROW_DRAWING: 'endArrowDrawing',
        START_MOSAIC_DRAWING: 'startMosaicDrawing',
        END_MOSAIC_DRAWING: 'endMosaicDrawing',
        EMPTY_REDO_STACK: 'emptyRedoStack',
        EMPTY_UNDO_STACK: 'emptyUndoStack',
        PUSH_UNDO_STACK: 'pushUndoStack',
        PUSH_REDO_STACK: 'pushRedoStack',
        ACTIVATE_TEXT: 'activateText',
        APPLY_FILTER: 'applyFilter',
        EDIT_TEXT: 'editText',
        MOUSE_DOWN: 'mousedown',
        CHANGE_ZOOM: 'changeZoom'
    },

    /**
     * Editor states
     */
    states: util.keyMirror(
        'NORMAL',
        'CROP',
        'FREE_DRAWING',
        'LINE',
        'ARROW',
        'MOSAIC',
        'TEXT',
        'SHAPE',
        'PAN'
    ) as States,

    /**
     * Shortcut key values
     */
    keyCodes: {
        Z: 90,
        Y: 89,
        SHIFT: 16,
        BACKSPACE: 8,
        DEL: 46
    },

    /**
     * Fabric object options
     */
    fObjectOptions: {
        SELECTION_STYLE: {
            borderColor: '#118BFB',
            cornerColor: '#FFFFFF',
            cornerStrokeColor: '#118BFB',
            cornerSize: 12,
            padding: 1,
            originX: 'center',
            originY: 'center',
            transparentCorners: false,
            cornerStyle: 'circle'
        }
    },

    rejectMessages: {
        flip: 'The flipX and flipY setting values are not changed.',
        rotation: 'The current angle is same the old angle.',
        loadImage: 'The background image is empty.',
        isLock: 'The executing command state is locked.',
        undo: 'The promise of undo command is reject.',
        redo: 'The promise of redo command is reject.'
    },

    MOUSE_MOVE_THRESHOLD: 10
};

export default consts;
