name: Example Build & Deploy to GitHub Pages
on:
  push:
    branches:
      - master
    tags:
      - v1
    paths:
      - 'src/**'
      - 'demo/**'
      - '.github/**'
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install & build 🔧
        run: |
          pnpm install --frozen-lockfile
          pnpm build:demo
        env:
          CI: true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist-demo
          git-config-name: ${{ secrets.GIT_CONFIG_NAME }}
          git-config-email: ${{ secrets.GIT_CONFIG_EMAIL }}
